In [1]:
import numpy as np
import pandas as pd 
import scipy as sp


In [3]:
glodap = pd.read_csv("GLODAPv2_2020_A16_Atlantic.csv")
glodap

Year  Month  Cruise  Latitude  Longitude  Depth  Salinity  Temperature  \
0      1988      7     322    63.210    -20.005      2    34.977      10.7000   
1      1988      7     322    63.210    -20.005     62    35.111       8.3770   
2      1988      7     322    63.210    -20.005    101    35.141       7.7510   
3      1988      7     322    63.210    -20.005    151    35.146       7.5580   
4      1988      7     322    63.210    -20.005    201    35.148       7.4630   
5      1988      7     322    63.210    -20.005    251    35.144       7.3510   
6      1988      7     322    63.210    -20.005    301    35.144       7.2990   
7      1988      7     322    63.210    -20.005    351    35.142       7.2350   
8      1988      7     322    63.210    -20.005    401    35.139       7.1290   
9      1988      7     322    63.210    -20.005    449    35.136       7.0580   
10     1988      7     322    63.210    -20.005    500    35.128       6.9490   
11     1988      7     322    63.210    -20.005    540    35.126       6.8470   
12     1988      7     322    63.210    -20.005    575    35.119       6.7490   
13     1988      7     322    63.210    -20.005    599    35.119       6.7190   
14     1988      7     322    63.210    -20.005    626    35.110       6.5760   
15     1988      7     322    63.133    -20.007      8    35.039      10.9740   
16     1988      7     322    63.133    -20.007     33    35.081       9.2200   
17     1988      7     322    63.133    -20.007     62    35.105       8.3460   
18     1988      7     322    63.133    -20.007    153    35.137       7.5310   
19     1988      7     322    63.133    -20.007    202    35.141       7.3600   
20     1988      7     322    63.133    -20.007    252    35.141       7.2590   
21     1988      7     322    63.133    -20.007    302    35.140       7.2000   
22     1988      7     322    63.133    -20.007    352    35.136       7.1280   
23     1988      7     322    63.133    -20.007    402    35.135       7.0690   
24     1988      7     322    63.133    -20.007    452    35.129       6.9470   
25     1988      7     322    63.133    -20.007    501    35.125       6.8130   
26     1988      7     322    63.133    -20.007    551    35.107       6.5380   
27     1988      7     322    63.133    -20.007    601    35.094       6.3270   
28     1988      7     322    63.133    -20.007    650    35.079       6.0560   
29     1988      7     322    63.133    -20.007    699    35.068       5.7910   
...     ...    ...     ...       ...        ...    ...       ...          ...   
18921  2014      1    1042   -59.501    -30.919   1232    34.676       0.2523   
18922  2014      1    1042   -59.501    -30.919   1429    34.672       0.1664   
18923  2014      1    1042   -59.501    -30.919   1723    34.668       0.0604   
18924  2014      1    1042   -59.501    -30.919   2018    34.663      -0.0177   
18925  2014      1    1042   -59.501    -30.919   2313    34.662      -0.0604   
18926  2014      1    1042   -59.501    -30.919   2704    34.660      -0.0712   
18927  2014      1    1042   -59.501    -30.919   3094    34.659      -0.0771   
18928  2014      1    1042   -59.501    -30.919   3484    34.655      -0.1267   
18929  2014      1    1042   -59.501    -30.919   3660    34.655      -0.1161   
18930  2014      1    1042   -60.013    -30.895      3    33.276      -0.1320   
18931  2014      1    1042   -60.013    -30.895     17    33.454      -0.3014   
18932  2014      1    1042   -60.013    -30.895     38    33.916      -1.2180   
18933  2014      1    1042   -60.013    -30.895     57    34.067      -1.5482   
18934  2014      1    1042   -60.013    -30.895     98    34.256      -1.4296   
18935  2014      1    1042   -60.013    -30.895    147    34.443      -0.7942   
18936  2014      1    1042   -60.013    -30.895    196    34.557      -0.1801   
18937  2014      1    1042   -60.013    -30.895    245    34.603       0.0949   
18938  2014      1    1042   -60.013  

In [12]:
#masking and averaging
glodap[glodap['Month'] == 7]['Temperature'].mean()

9.519139910695301

In [16]:
#masking with multiple conditions
glodap[(glodap["Month"] == 7) & (glodap['Year'] == 1988)]

Year  Month  Cruise  Latitude  Longitude  Depth  Salinity  Temperature  \
0    1988      7     322    63.210    -20.005      2    34.977       10.700   
1    1988      7     322    63.210    -20.005     62    35.111        8.377   
2    1988      7     322    63.210    -20.005    101    35.141        7.751   
3    1988      7     322    63.210    -20.005    151    35.146        7.558   
4    1988      7     322    63.210    -20.005    201    35.148        7.463   
5    1988      7     322    63.210    -20.005    251    35.144        7.351   
6    1988      7     322    63.210    -20.005    301    35.144        7.299   
7    1988      7     322    63.210    -20.005    351    35.142        7.235   
8    1988      7     322    63.210    -20.005    401    35.139        7.129   
9    1988      7     322    63.210    -20.005    449    35.136        7.058   
10   1988      7     322    63.210    -20.005    500    35.128        6.949   
11   1988      7     322    63.210    -20.005    540    35.126        6.847   
12   1988      7     322    63.210    -20.005    575    35.119        6.749   
13   1988      7     322    63.210    -20.005    599    35.119        6.719   
14   1988      7     322    63.210    -20.005    626    35.110        6.576   
15   1988      7     322    63.133    -20.007      8    35.039       10.974   
16   1988      7     322    63.133    -20.007     33    35.081        9.220   
17   1988      7     322    63.133    -20.007     62    35.105        8.346   
18   1988      7     322    63.133    -20.007    153    35.137        7.531   
19   1988      7     322    63.133    -20.007    202    35.141        7.360   
20   1988      7     322    63.133    -20.007    252    35.141        7.259   
21   1988      7     322    63.133    -20.007    302    35.140        7.200   
22   1988      7     322    63.133    -20.007    352    35.136        7.128   
23   1988      7     322    63.133    -20.007    402    35.135        7.069   
24   1988      7     322    63.133    -20.007    452    35.129        6.947   
25   1988      7     322    63.133    -20.007    501    35.125        6.813   
26   1988      7     322    63.133    -20.007    551    35.107        6.538   
27   1988      7     322    63.133    -20.007    601    35.094        6.327   
28   1988      7     322    63.133    -20.007    650    35.079        6.056   
29   1988      7     322    63.133    -20.007    699    35.068        5.791   
..    ...    ...     ...       ...        ...    ...       ...          ...   
523  1988      7     322    45.980    -20.003   1429    35.044        4.869   
524  1988      7     322    45.980    -20.003   1697    34.941        4.001   
525  1988      7     322    45.980    -20.003   1964    34.924        3.717   
526  1988      7     322    45.980    -20.003   2249    34.943        3.559   
527  1988      7     322    45.980    -20.003   2637    34.965        3.277   
528  1988      7     322    45.980    -20.003   3020    34.948        2.920   
529  1988      7     322    45.980    -20.003   3397    34.932        2.723   
530  1988      7     322    45.980    -20.003   3803    34.917        2.598   
531  1988      7     322    45.980    -20.003   4214    34.910        2.591   
532  1988      7     322    45.980    -20.003   4829    34.908        2.647   
533  1988      7     322    45.485    -20.012     56    35.762       13.721   
534  1988      7     322    45.485    -20.012    107    35.688       12.791   
535  1988      7     322    45.485    -20.012    207    35.653       12.231   
536  1988      7     322    45.485    -20.012    306    35.587       11.710   
537  1988      7     322    45.485    -20.012    406    35.491       11.134   
538  1988      7     322    45.485    -20.012    574    35.409       10.321   
539  1988      7     322    45.485    -20.012    698    35.314        9.339   
540  1988      7     322    45.485    -20.012    795    35.233        8.183   
541  1988      7     322    45.485    -20.012    894   

In [17]:
#getting all unique Year entries in the "Year" column (called series)
glodap['Year'].unique()

array([1988, 1991, 1993, 2003, 2005, 1998, 2011, 2013, 2014])

In [18]:
glodap['Month'].unique()

array([ 7,  8,  6,  1,  2,  4,  5,  9, 10, 12])

In [20]:
#all unique year entries in all rows that have "Month" == 7 entry
glodap[glodap['Month'] == 7]["Year"].unique()

array([1988, 1991, 1993, 2003, 2011])